export const ACTION_CONTACT_EDIT = 'ACTION_CONTACT_EDIT';
export const ACTION_CONTACT_ADD = 'ACTION_CONTACT_ADD';

export const TYPE_INCOMING_CALL = 1;
export const TYPE_INCOMING_VIDEO_CALL = 2;
export const TYPE_MISSED_CALL = 3;
